<?php

namespace Database\Seeders;

use App\Models\SchoolReporting;
use Illuminate\Database\Seeder;

class SchoolReportingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $schoolReporting = [
            [
                'id' => 1,
                'station' => "Provincial Office",
                'name_of_member' => "Sibanda Thabani",
                'designation' => "Deputy Director Secondary",
                'msisdn' => "+263 715 872 812 / +263 786 465 521",
                'email' => "sibandathabani.5821@gmail.com",
                'province_id' => 2,
                'country_code' => "ZW",
                'status' => 1,
                'created_at' => '2023-03-15 19:14:42',
                'updated_at' => '2023-03-15 19:14:42',
            ],
            [
                'id' => 2,
                'station' => "Provincial Office",
                'name_of_member' => "Mthethwa Mbizo",
                'designation' => "A/Deputy Director HR",
                'msisdn' => "0772 987 052 / 0715 240 815",
                'email' => "mbizomthethwa@gmail.com",
                'province_id' => 2,
                'country_code' => "ZW",
                'status' => 1,
                'created_at' => '2023-03-15 19:14:42',
                'updated_at' => '2023-03-15 19:14:42',
            ],
            [
                'id' => 3,
                'station' => "Provincial Office",
                'name_of_member' => "Dube Elitha",
                'designation' => "A/Chief Accountant",
                'msisdn' => "0773 562 076",
                'email' => "elitahdube@gmail.com",
                'province_id' => 2,
                'country_code' => "ZW",
                'status' => 1,
                'created_at' => '2023-03-15 19:14:42',
                'updated_at' => '2023-03-15 19:14:42',
            ],
            [
                'id' => 4,
                'station' => "Provincial Office",
                'name_of_member' => "Chilufya Bukelani M",
                'designation' => "Schools inspector SPPRS",
                'msisdn' => "0777 994 422",
                'email' => "sibandathabani.5821@gmail.com",
                'province_id' => 2,
                'country_code' => "ZW",
                'status' => 1,
                'created_at' => '2023-03-15 19:14:42',
                'updated_at' => '2023-03-15 19:14:42',
            ],
            [
                'id' => 5,
                'station' => "Mzilikazi",
                'name_of_member' => "Lubinda stephen",
                'designation' => "Schools Inspector",
                'msisdn' => "0773383511",
                'email' => "stephenlubssgmail.com",
                'province_id' => 2,
                'country_code' => "ZW",
                'status' => 1,
                'created_at' => '2023-03-15 19:14:42',
                'updated_at' => '2023-03-15 19:14:42',
            ],
            [
                'id' => 6,
                'station' => "Mzilikazi",
                'name_of_member' => "Nanziwe Kumalo",
                'designation' => "DRT",
                'msisdn' => "0776448441",
                'email' => "nanziwekumalo2gmail.com",
                'province_id' => 2,
                'country_code' => "ZW",
                'status' => 1,
                'created_at' => '2023-03-15 19:14:42',
                'updated_at' => '2023-03-15 19:14:42',
            ],
            [
                'id' => 7,
                'station' => "Mzilikazi",
                'name_of_member' => "Khethiwe ndlovu",
                'designation' => "DLLC",
                'msisdn' => "0733625558",
                'email' => "khethiwendlovu@gmail.com",
                'province_id' => 2,
                'country_code' => "ZW",
                'status' => 1,
                'created_at' => '2023-03-15 19:14:42',
                'updated_at' => '2023-03-15 19:14:42',
            ],
            [
                'id' => 8,
                'station' => "Imbizo",
                'name_of_member' => "Mambayo Joyce",
                'designation' => "Schools Inspector",
                'msisdn' => "0772748305",
                'email' => "joycemambayo@gmail.com",
                'province_id' => 2,
                'country_code' => "ZW",
                'status' => 1,
                'created_at' => '2023-03-15 19:14:42',
                'updated_at' => '2023-03-15 19:14:42',
            ],
            [
                'id' => 9,
                'station' => "Imbizo",
                'name_of_member' => "Dingani Dube",
                'designation' => "Accountant",
                'msisdn' => "0774333707",
                'email' => "dbdingani@gmail.com",
                'province_id' => 2,
                'country_code' => "ZW",
                'status' => 1,
                'created_at' => '2023-03-15 19:14:42',
                'updated_at' => '2023-03-15 19:14:42',
            ],
            [
                'id' => 10,
                'station' => "Imbizo",
                'name_of_member' => "Moyo Bekithemba",
                'designation' => "SPS",
                'msisdn' => "0773737692",
                'email' => "Tembamoyo65@gmail.com",
                'province_id' => 2,
                'country_code' => "ZW",
                'status' => 1,
                'created_at' => '2023-03-15 19:14:42',
                'updated_at' => '2023-03-15 19:14:42',
            ],
            [
                'id' => 11,
                'station' => "Imbizo",
                'name_of_member' => "Mpofu Sibusiswe",
                'designation' => "DLLC",
                'msisdn' => "0772344185",
                'email' => "sibusisiwempofu141@gmail.com",
                'province_id' => 2,
                'country_code' => "ZW",
                'status' => 1,
                'created_at' => '2023-03-15 19:14:42',
                'updated_at' => '2023-03-15 19:14:42',
            ],
            [
                'id' => 12,
                'station' => "Reigate",
                'name_of_member' => "Mhlaba Chad",
                'designation' => "Schools Inspector",
                'msisdn' => "0772916665",
                'email' => "hrreigate@gmail.com",
                'province_id' => 2,
                'country_code' => "ZW",
                'status' => 1,
                'created_at' => '2023-03-15 19:14:42',
                'updated_at' => '2023-03-15 19:14:42',
            ],
            [
                'id' => 13,
                'station' => "Reigate",
                'name_of_member' => "Gudza Tatenda",
                'designation' => "DRT",
                'msisdn' => "0773486352",
                'email' => "tetendag1970@gmail.com",
                'province_id' => 2,
                'country_code' => "ZW",
                'status' => 1,
                'created_at' => '2023-03-15 19:14:42',
                'updated_at' => '2023-03-15 19:14:42',
            ],
            [
                'id' => 14,
                'station' => "Reigate",
                'name_of_member' => "Mlambo Nondumiso",
                'designation' => "DLLC",
                'msisdn' => "0785382259",
                'email' => "ndumisomulambo14@gmail.com",
                'province_id' => 2,
                'country_code' => "ZW",
                'status' => 1,
                'created_at' => '2023-03-15 19:14:42',
                'updated_at' => '2023-03-15 19:14:42',
            ],
            [
                'id' => 15,
                'station' => "Khami",
                'name_of_member' => "Phiri Thabiso",
                'designation' => "A/Schools Inspector",
                'msisdn' => "0773472718",
                'email' => "thabigwate@gmail.com",
                'province_id' => 2,
                'country_code' => "ZW",
                'status' => 1,
                'created_at' => '2023-03-15 19:14:42',
                'updated_at' => '2023-03-15 19:14:42',
            ],
            [
                'id' => 16,
                'station' => "Khami",
                'name_of_member' => "Sibanda Sithandazile",
                'designation' => "Accountant",
                'msisdn' => "0773129264",
                'email' => "Sithandazilesibanda2gmail.com",
                'province_id' => 2,
                'country_code' => "ZW",
                'status' => 1,
                'created_at' => '2023-03-15 19:14:42',
                'updated_at' => '2023-03-15 19:14:42',
            ],
            [
                'id' => 17,
                'station' => "Khami",
                'name_of_member' => "Dube Zwelibanzi",
                'designation' => "DLLC",
                'msisdn' => "0774066189",
                'email' => "zwelibanzidube@gmail.com",
                'province_id' => 2,
                'country_code' => "ZW",
                'status' => 1,
                'created_at' => '2023-03-15 19:14:42',
                'updated_at' => '2023-03-15 19:14:42',
            ],
            [
                'id' => 18,
                'station' => "Bulawayo Central",
                'name_of_member' => "Ncube Jessie",
                'designation' => "Schools Inspector",
                'msisdn' => "+26371297635",
                'email' => "Jessiencube2gmail.com",
                'province_id' => 2,
                'country_code' => "ZW",
                'status' => 1,
                'created_at' => '2023-03-15 19:14:42',
                'updated_at' => '2023-03-15 19:14:42',
            ],
            [
                'id' => 19,
                'station' => "Bulawayo Central",
                'name_of_member' => "Behane Getrude",
                'designation' => "Accountant",
                'msisdn' => "0775858901",
                'email' => "Gettybehene2gmail.com",
                'province_id' => 2,
                'country_code' => "ZW",
                'status' => 1,
                'created_at' => '2023-03-15 19:14:42',
                'updated_at' => '2023-03-15 19:14:42',
            ],
            [
                'id' => 20,
                'station' => "Bulawayo Central",
                'name_of_member' => "Bafana stellah",
                'designation' => "DLLC",
                'msisdn' => "0772323360",
                'email' => "Stellabafana2@gmail.com",
                'province_id' => 2,
                'country_code' => "ZW",
                'status' => 1,
                'created_at' => '2023-03-15 19:14:42',
                'updated_at' => '2023-03-15 19:14:42',
            ],
            [
                'id' => 21,
                'station' => "Provincial Office",
                'name_of_member' => "Naison Chrispen",
                'designation' => "A/Deputy Director - SECNFE",
                'msisdn' => "+263772815900",
                'email' => "cnaiso.cn@gmail.com",
                'province_id' => 3,
                'country_code' => "ZW",
                'status' => 1,
                'created_at' => '2023-03-15 19:14:42',
                'updated_at' => '2023-03-15 19:14:42',
            ]
        ];

        foreach ($schoolReporting as $reporting) {
            SchoolReporting::query()->firstOrCreate($reporting, $reporting);
        }
    }
}
